# Generated by Django 6.0.1 on 2026-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='cleaned_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
